# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: MusicStory_development

test:
  <<: *default
  database: MusicStory_test

production:
  <<: *default
  database: MusicStory_production
  username: MusicStory
  password: <%= ENV['MUSICSTORY_DATABASE_PASSWORD'] %>
