# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: MusicStory_development

test:
  <<: *default
  database: MusicStory_test

production:
  <<: *default
  database: MusicStory_production
  username: MusicStory
  password: <%= ENV['MUSICSTORY_DATABASE_PASSWORD'] %>
