# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd81eddaf68dc42dd868d2d3758708b06e3ea1a2139464ea1ef94c7751d95ffa434f5f12fd290faf7db7518cef91e417917a0fe0d2d2dd62b86a7ccc4403944

test:
  secret_key_base: 074c9610339f701b4c16cbbdd587ae52124657cc9b83fcfcb3c85c761cd4e895bfd19552a10f7b473d65719d42b1c93303014a203aaeca33bffa45a6ee535613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
